paths:
  /products:
    post:
      tags:
        - productos
      summary: NewOrUpdateProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/parameters/schemas/NewOrUpdateProduct"
        required: true
      responses:
        "300":
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/Product"
        "700":
          description: Error server
    get:
      summary: All products obtained 
      tags:
        - productos
      responses:
        "200":
          description: All products obtained 
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/GetAllProducts"
        "500":
          description: Error Server.
  /products/{id}:
    get:
      summary: Product search by ID.
      tags:
        - productos
      parameters:
        - in: path
          name: id
          required: true
          description: Product ID
          schema:
            type: string
      responses:
        "200":
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/Product"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/ErrorGetById"
        "500":
          description: Error Server.
    put:
      tags:
        - productos
      summary: Products updated by id successfully
      parameters:
        - in: path
          name: id
          required: true
          description: Prodcut by id
          schema:
            type: string
      responses:
        "200":
          description: Product update
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/Product"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/ErrorGetById"
        "500":
          description: Error Server.
    delete:
      tags:
        - productos
      summary: Delete Product
      parameters:
        - in: path
          name: id
          required: true
          description: Product ID
          schema:
          type: string
      responses:
        "200":
          description: Product deleted ok.
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schema/products/ErrorGetById"
        "500":
          description: Error server.
  /cart:
    post:
      tags:
        - carrito
      summary: Cart created successfully
      responses:
        "200":
          description: Cart created successfully
          content:
            application/json:
              $ref: "#/components/schema/carts/Cart"
        "500":
          description: Error server.
  /cart/{id}:
    get:
      tags:
        - carrito
      summary: Obtain cart created successfully
      parameters:
        - in: path
          name: id
          required: true
          description: Cart by ID.
          schema:
          type: string
      responses:
        "200":
          description: Cart found
          content:
            application/json:
              $ref: "#/components/schema/carts/Cart"
        "404":
          description: Cart not found
        "500":
          description: Error Server
    put:
      tags:
        - carrito
      summary: Cart updated
      parameters:
        - in: path
          name: id
          required: true
          description: Product id
          schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            $ref: "#/components/parameters/schemas/Cart"
  /cart/{cid}/product/{pid}:
    post:
      tags:
        - carrito
      summary: Add product to cart
      security:
        - passport: []
      parameters:
        - in: path
          name: cid
          required: true
          description: Cart id
          schema:
            type: string
        - in: path
          name: pid
          required: true
          description: Product id
          schema:
            type: string
      responses:
        "200":
          description: Product added to cart
          content:
            application/json:
              $ref: "#/components/schema/carts/Cart"
        "500":
          description: Error server
    put:
      tags:
        - carrito
      summary: Cart product updated
      security:
        - passport: []
      parameters:
        - in: path
          name: cid
          required: true
          description: Cart id
          schema:
            type: string
        - in: path
          name: pid
          required: true
          description: Product id
          schema:
            type: string
      responses:
        "200":
          description: Product updated
          content:
            application/json:
              $ref: "#/components/schema/carts/Cart"
        "500":
          description: Server error
    delete:
      tags:
        - carrito
      summary: Delete product by cart
      security:
        - passport: []
      parameters:
        - in: path
          name: cid
          required: true
          description: Cart ID
          schema:
            type: string
        - in: path
          name: pid
          required: true
          description: Product ID
          schema:
            type: string
      responses:
        "200":
          description: Product successfully deleted
          content:
            application/json:
              $ref: "#/components/schema/carts/Cart"
        "500":
          description: Server error

components:
  securityScheme:
    passport:
      type: apiKey
      name: authorization
      in: header
